export const SEED_CORPUS_SCHEMA_VERSION = '1.0.0' as const;
export const SEED_COMPILER_SCHEMA_VERSION = '1.1.0' as const;
export const SEED_COMPILER_VERSION = '1.1.0' as const;
export const CANDIDATE_IDENTITY_VERSION = '1.0.0' as const;
export const OBSERVATION_IDENTITY_VERSION = '1.0.0' as const;

export const CANDIDATE_EVIDENCE_ROLES = ['PRIMARY', 'TRACE'] as const;

export const CANDIDATE_RESOLUTION_REASON_CODES = [
  'WEAK_ONLY_TRACE',
  'WEAK_ABSORBED',
  'QUALIFIED_PRIMARY',
  'EXPLICIT_ACTION_PRIMARY',
  'DERIVED_PRIMARY',
  'TARGET_CONTEXT_ABSORBED',
  'INDEPENDENT_PRIMARY',
] as const;

export const DERIVED_SUPPORT_COMPOSITION_TYPES = [
  'PRICE_TARGET_COMPOSITION',
  'SEARCH_TARGET_COMPOSITION',
  'DECISION_TARGET_COMPOSITION',
  'FINANCE_PREDICATE_COMPOSITION',
  'QUALIFICATION_PREDICATE_COMPOSITION',
  'EDUCATION_PREDICATE_COMPOSITION',
  'INVESTMENT_PREDICATE_COMPOSITION',
] as const;

export const CANDIDATE_MAPPING_STATUSES = [
  'MAPPED',
  'UNMAPPED',
  'AMBIGUOUS',
  'MULTI_INTENT',
  'CONFLICTED',
] as const;

export const CANDIDATE_QUALITY_FLAGS = ['LOW_INFORMATION'] as const;
