export const INTAKE_REPORT_SCHEMA_VERSION = '1.0.0' as const;
export const PROVENANCE_MANIFEST_SCHEMA_VERSION = '1.0.0' as const;
export const SEED_IDENTITY_VERSION = '1.0.0' as const;
export const SEED_SOURCE_CONVERSION_TOOL_VERSION = '1.0.0' as const;

export const INTAKE_RECORD_STATUSES = ['VALID', 'EMPTY', 'MALFORMED', 'UNSUPPORTED'] as const;
export const ACCEPTED_SOURCE_FORMATS = ['TXT'] as const;
export const ACCEPTED_SOURCE_ENCODINGS = ['UTF-8', 'UTF-8-BOM'] as const;
export const CONTENT_ORIGINS = ['AI_GENERATED', 'HUMAN_AUTHORED', 'MIXED', 'UNKNOWN'] as const;
export const PERSONAL_DATA_DECLARATIONS = [
  'NO_PERSONAL_OR_PRIVATE_DATA',
  'REVIEW_REQUIRED',
  'CONTAINS_PERSONAL_OR_PRIVATE_DATA',
] as const;
export const INTAKE_ERROR_CODES = [
  'UNSUPPORTED_FORMAT',
  'MALFORMED_ENCODING',
  'DECLARED_ENCODING_MISMATCH',
  'PRIVACY_DECLARATION_REQUIRED',
  'REPOSITORY_STORAGE_PERMISSION_REQUIRED',
  'RECORD_TOO_LONG',
] as const;
