export const INTAKE_REPORT_SCHEMA_VERSION = '1.0.0' as const;
export const PROVENANCE_MANIFEST_SCHEMA_VERSION = '1.0.0' as const;
export const SEED_IDENTITY_VERSION = '1.0.0' as const;
export const SEED_SOURCE_CONVERSION_TOOL_VERSION = '1.0.0' as const;
export const DOCX_EXTRACTION_VERSION = '1.0.0' as const;

export const MAX_SOURCE_ARTIFACT_BYTES = 8 * 1024 * 1024;
export const MAX_ZIP_ENTRY_COUNT = 256;
export const MAX_SINGLE_UNCOMPRESSED_ENTRY_BYTES = 8 * 1024 * 1024;
export const MAX_TOTAL_UNCOMPRESSED_BYTES = 16 * 1024 * 1024;
export const MAX_DOCUMENT_XML_BYTES = 4 * 1024 * 1024;

export const COZE_PROVENANCE_NOTICE =
  '本内容由 Coze AI 生成，请遵循相关法律法规及《人工智能生成合成内容标识办法》使用与传播。' as const;

export const INTAKE_RECORD_STATUSES = [
  'VALID',
  'EMPTY',
  'MALFORMED',
  'UNSUPPORTED',
  'SOURCE_PROVENANCE_NOTICE',
] as const;
export const ACCEPTED_SOURCE_FORMATS = ['TXT', 'DOCX'] as const;
export const ACCEPTED_SOURCE_ENCODINGS = ['UTF-8', 'UTF-8-BOM'] as const;
export const CONTENT_ORIGINS = ['AI_GENERATED', 'HUMAN_AUTHORED', 'MIXED', 'UNKNOWN'] as const;
export const PERSONAL_DATA_DECLARATIONS = [
  'NO_PERSONAL_OR_PRIVATE_DATA',
  'REVIEW_REQUIRED',
  'CONTAINS_PERSONAL_OR_PRIVATE_DATA',
] as const;
export const INTAKE_ERROR_CODES = [
  'UNSUPPORTED_FORMAT',
  'MALFORMED_ENCODING',
  'DECLARED_ENCODING_MISMATCH',
  'PRIVACY_DECLARATION_REQUIRED',
  'REPOSITORY_STORAGE_PERMISSION_REQUIRED',
  'RECORD_TOO_LONG',
  'SOURCE_ARTIFACT_CHECKSUM_MISMATCH',
  'SOURCE_ARTIFACT_TOO_LARGE',
  'ZIP_ENTRY_LIMIT_EXCEEDED',
  'ZIP_ENTRY_TOO_LARGE',
  'ZIP_TOTAL_UNCOMPRESSED_LIMIT_EXCEEDED',
  'DOCUMENT_XML_TOO_LARGE',
  'INVALID_DOCX_CONTAINER',
  'DOCUMENT_XML_MISSING',
  'MALFORMED_DOCUMENT_XML',
  'UNSAFE_XML_STRUCTURE',
  'UNSUPPORTED_DOCX_STRUCTURE',
  'PROVENANCE_NOTICE_STRUCTURE_MISMATCH',
] as const;
