export const ACCESS_METHODS = [
  'FREE_PUBLIC',
  'OFFICIAL_API',
  'AUTHORIZED_PROVIDER',
  'COMMERCIAL_PROVIDER',
] as const;

export const COST_MODELS = ['FREE', 'PER_CALL', 'SUBSCRIPTION', 'QUOTA_ONLY', 'UNKNOWN'] as const;
export const SOURCE_AUTHORITY_STATUSES = ['AUTHORIZED', 'PENDING', 'DENIED', 'UNKNOWN'] as const;
export const SOURCE_HEALTH_STATUSES = ['HEALTHY', 'DEGRADED', 'UNAVAILABLE', 'UNKNOWN'] as const;
export const MONITORING_STATES = ['ACTIVE', 'PAUSED', 'SOURCE_UNAVAILABLE', 'COMPLETED'] as const;
export const PLATFORMS = ['DOUYIN', 'WECHAT_VIDEO_ACCOUNT', 'SEARCH_INDEX', 'OTHER'] as const;
export const SOURCE_COMMENT_ID_KINDS = ['PLATFORM_STABLE', 'SOURCE_LOCAL', 'ABSENT'] as const;
export const COMMENT_DELETION_STATES = ['ACTIVE', 'DELETED', 'UNKNOWN'] as const;
export const COMMENT_IDENTITY_STRENGTHS = ['STRONG', 'WEAK_FINGERPRINT'] as const;

export const ACQUISITION_MONITORING_SCHEMA_VERSION = '1.0.0' as const;
