import type { PrismaClient } from '@prisma/client';
import type { KeywordCategoryRecord, KeywordCategoryRepository, Page, PageRequest, PersistenceTransactionContext } from '@re-agent/shared';
import { toCategoryRecord } from '../../infrastructure/persistence/keyword.mapper';
import { resolvePrismaExecutor } from '../../infrastructure/persistence/prisma-transaction-context';
export class PrismaKeywordCategoryRepository implements KeywordCategoryRepository {
  constructor(private readonly prisma: PrismaClient) {}
  async create(input: Omit<KeywordCategoryRecord, 'id' | 'createdAt' | 'updatedAt'>, context?: PersistenceTransactionContext): Promise<KeywordCategoryRecord> { return toCategoryRecord(await resolvePrismaExecutor(this.prisma, context).keywordCategory.create({ data: input })); }
  async findById(id: string, context?: PersistenceTransactionContext): Promise<KeywordCategoryRecord | null> { const row = await resolvePrismaExecutor(this.prisma, context).keywordCategory.findUnique({ where: { id } }); return row ? toCategoryRecord(row) : null; }
  async list(page: PageRequest, context?: PersistenceTransactionContext): Promise<Page<KeywordCategoryRecord>> { const client = resolvePrismaExecutor(this.prisma, context); const [items, total] = await Promise.all([client.keywordCategory.findMany({ orderBy: [{ code: 'asc' }], skip: (page.page - 1) * page.pageSize, take: page.pageSize }), client.keywordCategory.count()]); return { items: items.map(toCategoryRecord), page: page.page, pageSize: page.pageSize, total }; }
  async update(id: string, expectedUpdatedAt: Date, input: Partial<Pick<KeywordCategoryRecord, 'name' | 'parentId' | 'status'>>, context?: PersistenceTransactionContext): Promise<KeywordCategoryRecord | null> { const client = resolvePrismaExecutor(this.prisma, context); const result = await client.keywordCategory.updateMany({ where: { id, updatedAt: expectedUpdatedAt }, data: input }); return result.count ? this.findById(id, context) : null; }
  async hasChildren(id: string, context?: PersistenceTransactionContext): Promise<boolean> { return Boolean(await resolvePrismaExecutor(this.prisma, context).keywordCategory.findFirst({ where: { parentId: id }, select: { id: true } })); }
  async isReferenced(id: string, context?: PersistenceTransactionContext): Promise<boolean> { return Boolean(await resolvePrismaExecutor(this.prisma, context).keyword.findFirst({ where: { categoryId: id }, select: { id: true } })); }
  async detectCyclePath(id: string, proposedParentId: string | null, context?: PersistenceTransactionContext): Promise<readonly string[] | null> { if (!proposedParentId) return null; const client = resolvePrismaExecutor(this.prisma, context); const rows = await client.$queryRaw<Array<{ id: string }>>`WITH RECURSIVE ancestors AS (SELECT id, parent_id FROM keyword_categories WHERE id = ${proposedParentId} UNION ALL SELECT category.id, category.parent_id FROM keyword_categories category JOIN ancestors ON category.id = ancestors.parent_id) SELECT id FROM ancestors`; const path = rows.map((row) => row.id); return path.includes(id) ? path : null; }
}
